AWSTemplateFormatVersion: "2010-09-09"
Description: "A Sample template building out a simple Linux box"
  
#VPC-ID: vpc-26b83941
#VPC-Name: CL1-VPC
#TODO:  Add creation of VPC

Parameters:
  envParam:
    Type: String
    #list of allowed params
    AllowedValues: ['us-west-2']
            
            
#If setting is not defined in VPC, define it here.
  InstanceTypeParam: 
    Type: String
    Default: t2.micro
  ImageIdParam:
    Type: String
    Default: ami-1e299d7e
  ServerNameParam:
    Type: String
    Default: CL1-Server
  BackupFlagParam:
    Type: String
    Default: True
    
    
# If setting is related to VPC, define it here.
Mappings:
  config:
    us-west-2:
      SubnetId: subnet-f6cb6f91
      KeyName: CL1
      EIP: 52.24.225.9
      
      
#Define resources.  All Resource Attributes should be defined above.

Resources:

  IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref MyEC2Instance
      EIP: !FindInMap [config, !Ref envParam, EIP] 

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageIdParam
      KeyName: !FindInMap [config, !Ref envParam, KeyName] 
      InstanceType: !Ref InstanceTypeParam
      #Assign the subnet defined in VPC
      SubnetId: !FindInMap [config, !Ref envParam, SubnetId] 
      #Reference Security Groups Below. When referencing SG's from VPC, it must be done by groupID not name.
      SecurityGroupIds: [!GetAtt SSHSecurityGroup.GroupId, !GetAtt WebSecurityGroup.GroupId]
      Tags: 
        - Key: Name
          Value: !Ref ServerNameParam
        - Key: ScheduledBackup
          Value: !Ref BackupFlagParam
      
      
# define securityGroups to be assigned to Instances
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and www
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
      #Assign the SG to a specific VPC
      VpcId: vpc-26b83941
            
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
      #Assign the SG to a specific VPC
      VpcId: vpc-26b83941
      
      
Outputs:
    ServerIP:
      Description: Server IP Address
      Value: !GetAtt MyEC2Instance.PrivateIp
    
    
    

