AWSTemplateFormatVersion: "2010-09-09"
Description: A Sample template building out a simple Linux box
  
#VPC-ID: vpc-26b83941
#VPC-Name: CL1-VPC

Parameters:
  InstanceTypeParam: 
    Type: String
    Default: t2.micro
  KeyNameParam:
    Type: AWS::EC2::KeyPair::KeyName
    Default: "CL1"
    

Resources:

#Create EC2 Instance

  IPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref MyEC2Instance
      EIP: 52.24.225.9

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-1e299d7e
      KeyName: !Ref KeyNameParam
      InstanceType: !Ref InstanceTypeParam
      #Assign the subnet defined in VPC
      SubnetId: subnet-f6cb6f91 
      #Reference Security Groups Below. When referencing SG's from VPC, it must be done by groupID not name.
      SecurityGroupIds: [!GetAtt SSHSecurityGroup.GroupId, !GetAtt WebSecurityGroup.GroupId]
      
      
# define securityGroups to be assigned to Instances
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and www
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
      #Assign the SG to a specific VPC
      VpcId: vpc-26b83941
            
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
      #Assign the SG to a specific VPC
      VpcId: vpc-26b83941
      

    
    
    

